# fly.toml app configuration file generated for fantasy500 on 2023-05-27T11:19:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fantasy500"
primary_region = "ord"
console_command = "/rails/bin/rails console"

[env]
  HOST = "fantasy500.site"
  DRIVERS_API = "https://feeds.indycar.com/driversfeed.json"
  GRID_API = "https://indycarsso.blob.core.windows.net/racecontrol/livegrid.json"
  INDYCAR_URL = "https://www.indycar.com/Drivers"
  SCORING_API = "https://indycarsso.blob.core.windows.net/racecontrol/timingscoring-ris.json"
  SCORING_EVENT_NAME = "Indianapolis 500"
  SCORING_UPDATES = "disabled"
  LANG = "en_US.UTF-8"
  RACK_ENV = "production"
  RAILS_ENV = "production"
  SMTP_HOST = "smtp.postmarkapp.com"
  SMTP_PORT = "587"

[processes]
  web = "bundle exec puma -C config/puma.rb"
  worker = "bundle exec sidekiq -t 25"

[deploy]
  release_command = "bundle exec rake db:migrate data:migrate"

[http_service]
  processes = ["web"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
